### PR TITLE
Drop report tool

### PR DESCRIPTION
**Pull request by rma-tom**

### CODE REVIEW

**Comment by rma-tom** [comment]
Removing callite-report-tool from wrims project as it's duplicated in its own project

**Comment by hxiedwr** [comment]
Hi Tom,

I don’t want to make any mistake. Please drop the callite report tool from wrims-devops branch.

I want to keep master branch not touched. If heclib 7 upgrade fail, we can go back to master branch.

I will disapprove the drop from master branch.

Thank you,

Hao
________________________________

**Comment by rma-tom** [comment]
Hi Hao

Good catch! I had intended to make the merge into the HecDSS7 branch. I didn’t want to change master! Reviews are a good thing.

Cheers
Tom

**Comment by hxiedwr** [comment]
Great. Thank you.




________________________________

**Pull request closed without merging**
